package com.toracshalby.emergencymobile.network


const val WEBSOCKET_URL =
    "INSERISCI_OUTPUT_WEBSOCKET_ENDPOINT"

const val UPLOAD_URL_ENDPOINT =
    "INSERISCI_OUTPUT_UPLOAD_URL_ENDPOINT"

const val EMERGENCY_ENDPOINT =
    "INSERISCI_OUTPUT_EMERGENCY_ENDPOINT"

const val CAMERA_TEST_ENDPOINT =
    "INSERISCI_OUTPUT_CAMERA_TEST_ENDPOINT"